---
# Só mude aqui!!!!
author: "Luiz Gustavo dos Santos "
title: "Relatório da Aula Prática 01 - Descrição do experimento da catapulta "
bibliography: referencias.bib
# A partir daqui nao faca alteracoes!!!!!
link-citations: true
csl: associacao-brasileira-de-normas-tecnicas-ipea.csl
subtitle: "<a href='https://bendeivide.github.io/courses/epaec/' target='_blank'>Estatística e Probabilidade</a> </br> <a href='https://bendeivide.github.io' target='_blank'>Prof. Ben Dêivide (DEFIM/CAP/UFSJ)</a>"
include-before-body: header.html
date: now
date-format: "DD/MM/YYYY, HH:mm"
lang: pt-BR
format:
  html:
    toc: true
    number-sections: true
    theme: bootstrap
    #css: styles.css
    code-fold: true
    code-tools: true
execute:
  echo: true
  warning: false
  message: false
---


## 📌 Introdução

O experimento baseia-se no lançamento repetido de uma bolinha feito a partir de uma catapulta com diversos parâmetros de configurações, como posição do elástico, posição da bolinha e ângulo de disparo.



## 🎯 Objetivos

### Objetivo geral

Analisar e comparar as distâncias percorrida por uma bolinha ao ser lançada por uma catapulta.

### Objetivos específicos

- Coletar dados experimentais  
- Aplicar estatística descritiva  
- Construir gráficos  
- Interpretar resultados  

---

## 📚  Fundamentação Teórica

Veja na tabela os dados coletados:

Distância percorrida pela bolinha

\center

<style type="text/css">
.tg  {border-collapse:collapse;border-color:#bbb;border-spacing:0;}
.tg td{background-color:#E0FFEB;border-color:#bbb;border-style:solid;border-width:0px;color:#594F4F;
  font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{background-color:#9DE0AD;border-color:#bbb;border-style:solid;border-width:0px;color:#493F3F;
  font-family:Arial, sans-serif;font-size:14px;font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-996f{background-color:#C2FFD6;border-color:inherit;text-align:center;vertical-align:top}
.tg .tg-c3ow{border-color:inherit;text-align:center;vertical-align:top}
</style>
<table class="tg" style="undefined;table-layout: fixed; width: 286px"><colgroup>
<col style="width: 130px">
<col style="width: 156px">
</colgroup>
<thead>
  <tr>
    <th class="tg-c3ow">LANÇAMENTO</th>
    <th class="tg-c3ow">DISTÂNCIA (Mts)</th>
  </tr></thead>
<tbody>
  <tr>
    <td class="tg-996f">1</td>
    <td class="tg-996f">1,96</td>
  </tr>
  <tr>
    <td class="tg-c3ow">2</td>
    <td class="tg-c3ow">1,95</td>
  </tr>
  <tr>
    <td class="tg-996f">3</td>
    <td class="tg-996f">1,99</td>
  </tr>
  <tr>
    <td class="tg-c3ow">4</td>
    <td class="tg-c3ow">1,93</td>
  </tr>
  <tr>
    <td class="tg-996f">5</td>
    <td class="tg-996f">2,05</td>
  </tr>
  <tr>
    <td class="tg-c3ow">6</td>
    <td class="tg-c3ow">2,13</td>
  </tr>
  <tr>
    <td class="tg-996f">7</td>
    <td class="tg-996f">2,8</td>
  </tr>
  <tr>
    <td class="tg-c3ow">8</td>
    <td class="tg-c3ow">1,99</td>
  </tr>
  <tr>
    <td class="tg-996f">9</td>
    <td class="tg-996f">2,5</td>
  </tr>
  <tr>
    <td class="tg-c3ow">10</td>
    <td class="tg-c3ow">2,8</td>
  </tr>
  <tr>
    <td class="tg-996f">11</td>
    <td class="tg-996f">1,99</td>
  </tr>
  <tr>
    <td class="tg-c3ow">12</td>
    <td class="tg-c3ow">1,88</td>
  </tr>
  <tr>
    <td class="tg-996f">13</td>
    <td class="tg-996f">2,01</td>
  </tr>
  <tr>
    <td class="tg-c3ow">14</td>
    <td class="tg-c3ow">1,97</td>
  </tr>
  <tr>
    <td class="tg-996f">15</td>
    <td class="tg-996f">2</td>
  </tr>
  <tr>
    <td class="tg-c3ow">16</td>
    <td class="tg-c3ow">1,72</td>
  </tr>
  <tr>
    <td class="tg-996f">17</td>
    <td class="tg-996f">1,86</td>
  </tr>
  <tr>
    <td class="tg-c3ow">18</td>
    <td class="tg-c3ow">1,95</td>
  </tr>
  <tr>
    <td class="tg-996f">19</td>
    <td class="tg-996f">1,92</td>
  </tr>
  <tr>
    <td class="tg-c3ow">20</td>
    <td class="tg-c3ow">2,03</td>
  </tr>
  <tr>
    <td class="tg-996f">21</td>
    <td class="tg-996f">1,71</td>
  </tr>
  <tr>
    <td class="tg-c3ow">22</td>
    <td class="tg-c3ow">1,64</td>
  </tr>
  <tr>
    <td class="tg-996f">23</td>
    <td class="tg-996f">1,87</td>
  </tr>
  <tr>
    <td class="tg-c3ow">24</td>
    <td class="tg-c3ow">1,96</td>
  </tr>
  <tr>
    <td class="tg-996f">25</td>
    <td class="tg-996f">1,93</td>
  </tr>
  <tr>
    <td class="tg-c3ow">26</td>
    <td class="tg-c3ow">1,77</td>
  </tr>
  <tr>
    <td class="tg-996f">27</td>
    <td class="tg-996f">1,95</td>
  </tr>
  <tr>
    <td class="tg-c3ow">28</td>
    <td class="tg-c3ow">1,93</td>
  </tr>
  <tr>
    <td class="tg-996f">29</td>
    <td class="tg-996f">1,98</td>
  </tr>
  <tr>
    <td class="tg-c3ow">30</td>
    <td class="tg-c3ow">1,96</td>
  </tr>
  <tr>
    <td class="tg-996f">31</td>
    <td class="tg-996f">1,98</td>
  </tr>
  <tr>
    <td class="tg-c3ow">32</td>
    <td class="tg-c3ow">1,68</td>
  </tr>
  <tr>
    <td class="tg-996f">33</td>
    <td class="tg-996f">1,82</td>
  </tr>
  <tr>
    <td class="tg-c3ow">34</td>
    <td class="tg-c3ow">1,84</td>
  </tr>
  <tr>
    <td class="tg-996f">35</td>
    <td class="tg-996f">1,9</td>
  </tr>
  <tr>
    <td class="tg-c3ow">36</td>
    <td class="tg-c3ow">1,87</td>
  </tr>
  <tr>
    <td class="tg-996f">37</td>
    <td class="tg-996f">1,67</td>
  </tr>
  <tr>
    <td class="tg-c3ow">38</td>
    <td class="tg-c3ow">1,51</td>
  </tr>
  <tr>
    <td class="tg-996f">39</td>
    <td class="tg-996f">1,68</td>
  </tr>
  <tr>
    <td class="tg-c3ow">40</td>
    <td class="tg-c3ow">1,72</td>
  </tr>
</tbody></table>

\center



### DADOS CALCULADOS A PARTIR DA COLETA:

Veja na tabela os dados calculados a partir das amostragem do experimento:

\center
<style type="text/css">
.tg  {border-collapse:collapse;border-color:#bbb;border-spacing:0;}
.tg td{background-color:#E0FFEB;border-bottom-width:1px;border-color:#bbb;border-style:solid;border-top-width:1px;
  border-width:0px;color:#594F4F;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;
  word-break:normal;}
.tg th{background-color:#9DE0AD;border-bottom-width:1px;border-color:#bbb;border-style:solid;border-top-width:1px;
  border-width:0px;color:#493F3F;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;overflow:hidden;
  padding:10px 5px;word-break:normal;}
.tg .tg-996f{background-color:#C2FFD6;border-color:inherit;text-align:center;vertical-align:top}
.tg .tg-c3ow{border-color:inherit;text-align:center;vertical-align:top}
.tg .tg-7btt{border-color:inherit;font-weight:bold;text-align:center;vertical-align:top}
.tg .tg-grbc{background-color:#C2FFD6;border-color:inherit;font-weight:bold;text-align:center;vertical-align:top}
</style>
<table class="tg" style="undefined;table-layout: fixed; width: 344px"><colgroup>
<col style="width: 156px">
<col style="width: 188px">
</colgroup>
<thead>
  <tr>
    <th class="tg-7btt">MÉDIA</th>
    <th class="tg-c3ow">1,945 Mts</th>
  </tr></thead>
<tbody>
  <tr>
    <td class="tg-grbc">VARIÂNCIA</td>
    <td class="tg-996f">0,6445</td>
  </tr>
  <tr>
    <td class="tg-7btt">DESVIO PADRÃO</td>
    <td class="tg-c3ow">0,254 Mts</td>
  </tr>
  <tr>
    <td class="tg-grbc">AMOSTRAGEM</td>
    <td class="tg-996f">40</td>
  </tr>
</tbody>
</table>


\center

---

## ⚙️ Metodologia


- Materiais utilizados: Catapulta de madeira, trena, bolinha de papel, mesa. 

- Procedimento: Foram realizados 40 lançamentos seguidos afim de se coletar a distância percorrida pela bolinha, com a catapulta configurada em determinada posição, a cada lançamento feito , usava-se a trena para medir a distãncia percorrida pela bolinha, afim de coletar dados. 

- Número de repetições: 40 repetições  

---

## 🔍 Resultados e Discussão

A distância média dos lançamentos foi de **1,945 metros**, ocorreu uma variância de **0,644 metros**, devido a fatores extrernos como a ação da gravidade dentro da sala e o desempenho do experimentador ao puxar a alavanca da catapulta, hora colocando mais força e hora colocando menos força. Isso é mostrado pelo desvio padrão de **0,254 metros**.
 Outro fator que deixa evidente a influência de fatores externos no experimento é a discrepância entre a distância de alguns lançamentos, visto que todos os lancamentos foram feitos com a catapulta em uma única configuração.
 A menor distãncia percorrida pela bolinha foi de **1,51 metros** e a maior distância foi de **2,80 metros**, o que indica uma provável existência de erro experimental, seja por parte de quem fez o lançamento, ou quem mediu as distâncias, ou quem anotou e lançou os dados no sistema ou até mesmo erro no própio equipamento (trena,catapulta).
  Pelas condições que tinhamos para realizar o experimento, os resultados se enquadram no que já esperavamos, visto que não estávamos em um laboratório própio para esse tipo de experimento, onde fatores externos são minimizados, o que resultaria na diminuição dessa variabilidade dos dados.



### 💬 Exemplo de como citar uma referência bibliográfica

Depois de inserido as informaçõe no arquivo **referencias.bib**, use:

- Segundo @Rbasico2022
- Tudo é um objeto em R [@Rbasico2022]

### 📊  Análise de Dados

```{r}
distancia <- c(10.2, 9.8, 10.5, 10.1, 9.9, 10.3)
distancia
```

## 🧠 Considerações finais

Apresente uma síntese dos principais pontos observados no experimento.

- Retome o objetivo da prática e indique se ele foi alcançado.
- Destaque os principais aprendizados obtidos.
- Comente brevemente sobre a qualidade dos dados coletados.
- Sugira possíveis melhorias no procedimento experimental.

Evite repetir apenas os resultados; foque nas **conclusões e reflexões** sobre a prática realizada.

## Aprenda Quarto

Acesse [Quarto](https://quarto.org/).

## 📖 Referências